machine:
  network:
    nameservers:
      - 192.168.1.1
    interfaces:
      - interface: eno1
        dhcp: false
        addresses:
          - 192.168.1.241/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
  install:
    disk: /dev/nvme0n1
    image: ghcr.io/siderolabs/installer:v1.13.0
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: worker-01
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 200GiB
